name: Add comment
on: [pull_request_target, issues]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add comment
        run: gh pr comment $NUMBER --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.number }}
          REPO: ${{ github.repository }}
          BODY: >
            Hi @${{ github.actor }}
            Please wait until one of our team see your PR
